source 'https://rubygems.org'

gem 'bundler'
gem 'chronic'
gem 'cucumber'
gem 'headless'
gem 'nokogiri'
gem 'rake'
gem 'selenium-webdriver'
gem 'syntax'
gem 'watir'
gem 'watir-webdriver'
gem 'watir-webdriver-performance'
gem 'page-object'
gem 'hashie'
gem 'minitest'

# gem 'watir-dom-wait'
# gem 'win32ole'
# gem 'cucumber', '3.1.0'
# gem 'selenium-webdriver', '3.7.0'
# gem 'minitest',  '5.10.3'
# gem 'hashie'
# group :development do
#   gem 'awesome_print', '1.8.0'
# end
