def map_assurancenet_displayloginaction_do
  @page_objects['assurancenet_displayloginaction_do'] =
                    {
                        # #Login
                        # 'full name' => "css^^.custom-combobox-input.ui-widget.ui-widget-content.ui-state-default.ui-corner-left.ui-autocomplete-input",
                        # 'submit login' => "xpath^^.//*[@type='submit']",
                        # 'role'=>"xpath^^//*[@id='change_role_select']",
                        
                        #Investigation Page objects
                        
                        # 'investigation' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[7]/a",
                        # 'violation date' => "xpath^^//*[@name='violationDate']",
                        # 'primary lookup' => "xpath^^//*[@id='1']/td[3]/div[1]/a",
                        # 'secondary lookup' => "xpath^^//*[@id='2']/td[3]/div[1]/a",
                        # 'tertiary lookup' => "xpath^^//*[@id='3']/td[3]/div[1]/a",
                        # 'fourth lookup' => "xpath^^//*[@id='4']/td[3]/div[1]/a",
                        # 'fifth lookup' => "xpath^^//*[@id='5']/td[3]/div[1]/a",
                        # 'firm identifier' => "xpath^^//*[@id='search_box']/div[10]/div[2]/input",
                        # 'firm lookup' => "xpath^^//*[@id='firmSearchForm']",
                        # 'submit' => "xpath^^//*[text()='Submit']",
                        # 'investigative plan' => "xpath^^.//*[@name='investPlan']",
                        # 'statute' => "xpath^^.//*[@name='statute']",
                        # 'primary investigation case type' => "xpath^^//*[@name='primInvestCaseType']",
                        # 'secondary investigation case type' => "xpath^^//*[@name='secInvestCaseType']",
                        # 'primary violation type' => "xpath^^//*[@name='primViolType']",
                        # 'secondary violation type' => "xpath^^//*[@name='secViolType']",
                        # 'predication code' => "xpath^^//*[@name='predicationCode']",
                        # 'food safety related' => "xpath^^//*[@name='foodSaftyRelated']",
                        # 'keywords' => "xpath^^//*[@name='keywords']",
                        # 'go' => "xpath^^.//*[text()='Go']",
                        # 'inv comments' => "xpath^^.//*[@id='rdComments']/div[2]/input",
                        # 'comment go' => "xpath^^.//*[@id='rdComments']/div[2]/a",
                        # 'actions' => "xpath^^.//*[@id='navigationAction']",
                        # 'investigation tab' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[11]/a",
                        # 'investigation file number' => "xpath^^//*[@id='search_box']/div[2]/div[2]/input",
                        # 'case' => "xpath^^.//*[@id='action_bar']/div[1]/div[4]",
                        # # 'search' => "xpath^^//*[@id='search_container']/div[3]/div[2]/a",
                        # # 'investigation file number' => "xpath^^//*[@id='search_box']/div[2]/div[2]/input",
                        # 'additional comments tab' => "xpath^^//*[@id='AddCommentActionForm']/table/tbody/tr/td/ul[2]/li[3]/a",
                        # 'additional comments' => "xpath^^//*[@id='att_container']/textarea",
                        # 'keywords' => "xpath^^//*[@name='keywords']",
                        # 'delegation of authority' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[3]/a",
                        # 'last name' => "xpath^^.//*[@name='searchLastName']",
                        # 'name search' => "xpath^^.//*[contains(text(),'Search')]",
                        # 'select radio button' => "xpath^^.//*[@value='224']",
                        # 'program area' => "xpath^^.//*[@id='office_dropdown']",
                        # 'role type' => "xpath^^.//*[@id='role_type_dropdown']",
                        # 'role name' => "xpath^^.//*[@id='role_type_input']",
                        # 'submit role' => "xpath^^.//*[@id='submit_role_button']",
                        # 'delegation submit' => "xpath^^.//*[@value='Submit']",
                        # 'investigation number' => "xpath^^//*[@id='search_table']/tbody/tr[2]/td[1]/a/span",
                        # 'food safety related' => "xpath^^.//*[@id='foodSafty_Related']",
                                                
                   # # Misconduct Page Objects
                   #      'misconduct investigation' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[6]/a",
                   #      'type' => "xpath^^ //*[@id='misInvType']",
                   #      'source' => "xpath^^ //*[@id='sourceType']",
                   #      'complaint notification date' => "xpath^^ //*[@id='complainantNotificationDate']",
                   #      'subject name' => "xpath^^ //*[@id='firstSubName']",
                   #      'investigation warranted' => "xpath^^//*[@id='invWarranted']",
                   #      'authorization letter sent date' => "xpath^^ //*[@id='authLetterDate']",
                   #      'investigation comment' => "xpath^^ //*[@name='initiateInvestigationComment']",
                   #      'save genearl info' => "xpath^^.//*[text()='Save General Info']",
                   #      'evidence collected tab' => "xpath^^.//*[text()='Evidence Collected']",
                   #
                   #      'evidence officer' => "xpath^^.//*[@name='evidenceOfficer']",
                   #      'add evidence' => "xpath^^.//*[@id='addEvidenceId']",
                   #      'evidence date' => "xpath^^//*[@id='newEvidence']/div[2]/div[2]/input",
                   #      'evidence record name' => "xpath^^//*[@id='newEvidence']/div[3]/div[2]/input",
                   #      'save evidence' => "xpath^^//*[@id='newEvidence']/div[1]/a[1]",
                   #      'evidence name' => "xpath^^//*[@id='evidence_table']/tbody/tr[2]/td[1]",
                   #
                   #
                   #      'forensic evidence collected tab' => "xpath^^.//*[text()='Forensic Evidence Collected']",
                   #      'save forensic evidence' => "xpath^^//*[@id='newEvidence']/div[1]/a[1]",
                   #      'go' => "xpath^^.//*[text()='Go']",
                   #      'action' => "xpath^^.//*[@id='navigationAction']",
                   #      'investigator go' => "xpath^^//*[@id='RMAssignment3']/a",
                   #      'logout' => "xpath^^//*[@id='leftnavmenu']/div[1]/div[/a/strong",
                   #
                   #      'view misconduct' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[4]/a",
                   #      'search' => "xpath^^//*[@id='search_container']/div[3]/div[2]/a",
                   #      'last page' => "xpath^^//*[@id='att_container']/table2]/tbody/tr/td/[a3]",
                   #      # 'case number' =>"xpath^^//*[@id='search_table']/tbody/tr11]/td1]/a/span"
                   #      'case number' => "xpath^^//*[@id='search_table']/tbody/tr[2]/td[1]/a/span",
                   #      'delete' => "xpath^^//*[@id='trashcan0']/a/img",
                   #      'delete tab' => "xpath^^.//*[text()='Delete']",
                   #      'additional comments changed' => "xpath^^//*[@name='additionalComments']",
                   #      'misconduct case number' => "xpath^^.//*[@name='caseNumber']",
                   #      'misconduct case id' => "xpath^^//*[@id='action_bar']/div[1]/div[4]",
                   #      'supv view misconduct' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[8]/a",
                   #
                   #Product Control Page Objects



  'product control'=>"xpath^^//*[@id='leftnavmenu']/div[3]/p[10]/a",
  'submit'=>"xpath^^//*[text()='Submit']",
  'custodian lookup'=>"xpath^^//*[@id='att_container']/div[7]/div[4]/div[3]/span/a",
  'tier'=>"xpath^^.//*[@name='risk']",
  'lookup submit'=>"xpath^^//*[text()='Submit']",
  'violator name'=>"xpath^^//*[@id='att_container']/div[4]/a[1]/span",
  'save general info'=>"xpath^^.//*[text()='Save General Info']",
  'date detained'=>"xpath^^//*[@name='startDateND']",
  'extended disposition'=>"xpath^^//*[@id='extendedDis']",
  'are owner and custodian the same?'=>"xpath^^//*[@id='copyCustodian_checkbox']",
  'product name'=>"xpath^^.//*[@id='detain_ProdName']",
  'coding name'=>"xpath^^.//*[@id='detain_Coding']",
  'unit type'=>"xpath^^.//*[@id='detain_Num']",
  'total number of units'=>"xpath^^.//*[@id='detainNumOfUnits']",
  'best buy date'=>"xpath^^//*[@id='bestBuyDateText']",
  'production date'=>"xpath^^//*[@id='productionDateText']",
  'establishment number'=>"xpath^^.//*[@id='detain_EstNum']",
  'location of detained articles'=>"xpath^^//*[@id='detain_LocationInfo']",
  'product weight'=>"xpath^^//*[@id='productWeightND']",
  'frozen'=>"xpath^^//*[@id='detain_Froze_checkbox']",
  'inspection'=>"xpath^^//*[@id='detain_Federal_checkbox']",
  'reason'=>"xpath^^//*[@id='detain_Misbranded_checkbox']",
  'detained tags'=>"xpath^^//*[@id='detain_TagNum']",
  'legal authority for detention'=>"xpath^^//*[@id='detain_Act_Poultry_checkbox']",
  'name and address of shipper'=>"xpath^^//*[@id='shipperInfo']",
  'name and address of seller'=>"xpath^^//*[@id='sellerInfo']",
  'point of shipment (origin)'=>"xpath^^//*[@id='pointShipment']",
  'transporter (origin)'=>"xpath^^//*[@id='transporter']",
  'was product sampled?'=>"xpath^^//*[@id='productSampled']",
  'freezer lot number'=>"xpath^^//*[@id='lotNum']",
  'name of owner notified'=>"xpath^^//*[@id='nameNotified']",
  'name(s) and address(es) of federal, state, or local authorities notified'=>"xpath^^.//*[@id='authoritiesNotifiedInfo']",
  'date owner notified'=>"xpath^^//*[@id='dateNotified']",
  'owner informed by'=>"xpath^^//*[@id='notifiedBy_TEL_checkbox']",
  'detention code'=>"xpath^^.//*[@name='detain_Code']",
  'description'=>"xpath^^.//*[@name='detain_ReasonInfo']",
  'voluntary destruction'=>"xpath^^//*[@id='voluntaryDestr_checkbox']",
  'destruction date'=>"xpath^^//*[@id='voluntaryDestrDate']",
  'placed embargo'=>"xpath^^//*[@id='placedEmbargo_checkbox']",
  'embargo description'=>"xpath^^//*[@id='placedEmbargoDesc']",
  'product weight ntd'=>"xpath^^//*[@name='productWeightNTD']",
  'terminated owner name'=>"xpath^^//*[@id='terminate_OwnerNotified']",
  'terminated detained tags'=>"xpath^^//*[@id='terminate_SerialNum']",
  'terminated detained date'=>"xpath^^//*[@id='terminate_TagDate']",
  'terminated owner notified date'=>"xpath^^.//*[@id='terminate_OwnerDate']",
  'terminated owner informed by'=>"xpath^^//*[@id='terminateBy_TEL_checkbox']",
  'notice of termination of detention form delivered to'=>"xpath^^//*[@id='terminate_DeliveredTo']",
  'ntd remarks'=>"xpath^^//*[@id='terminate_RemarksInfo']",
  'date product released'=>"xpath^^//*[@id='startDateText']",
  'donation'=>"xpath^^//*[@id='useDonation_checkbox']",
  'donation location'=>"xpath^^//*[@id='donationLocation']",
  'donation date'=>"xpath^^//*[@id='donationDate']",
  'donation organization'=>"xpath^^//*[@id='donationOrg']",
  'misbranded by ingredients'=>"xpath^^//*[@id='misbrandedByIngred']",
  'misbranded by label information'=>"xpath^^//*[@id='misbrandedByLabel']",
  'information description of product'=>"xpath^^//*[@id='persDescInfo']",
  'detained'=>"xpath^^//*[@id='persDetained_checkbox']",
  'product weight pun'=>"xpath^^//*[@name='productWeightPUN']",
  'owner name pun'=>"xpath^^//*[@name='ownerAgentNamePUN']",
  'date product destroyed'=>"xpath^^//*[@id='startDateText']",
  'product weight vdhfn'=>"xpath^^//*[@name='productWeightVDHFN']",
  'owner name vdhfn'=>"xpath^^//*[@name='ownerAgentNameVDHFN']",
  'save voluntay destruction of human food notice'=>"xpath^^.//*[text()='Save Voluntary Destruction of Human Food Notice']",
  'associated surveillance links'=>"xpath^^.//*[text()='Associated Surveillance Links']",
  'add surveillance links'=>"xpath^^//*[@id='prdCntrlSurvLinkForm']/div[3]/div[/a",
  'surveillance search'=>"xpath^^//*[@id='search_container']/div[3]/div[2]/a",
  'associated investigation links'=>"xpath^^.//*[text()='Associated Investigation Links']",
  'add investigation links'=>"xpath^^.//*[text()='Add Investigation Link']",
  'investigation file number'=>"xpath^^//*[@id='search_table']/tbody/tr[2]/td[1]",
  'view product control'=>"xpath^^//*[@id='leftnavmenu']/div[3]/p[15]/a",
  'custodian name'=>"xpath^^//*[@id='search_table']/tbody/tr[2]/td[1]/a/span",
  'product control search'=>"xpath^^//*[@id='search_container']/font/font/div[/div[2]/a",
  'custodian checkbox'=>"xpath^^.//*[@id='copyCustodian_checkbox']",
  'address'=>"xpath^^.//*[@name='firmInfo']",
  'mark of deletion check box'=>"xpath^^.//*[@name='investigationBean0].markedForRemoval']",
  'remove investigation link'=>"xpath^^.//*[@name='investigationBean0].markedForRemoval']",
  'logout'=>"xpath^^//*[@id='leftnavmenu']/div[1]/div[/a/strong",
  'search'=>"xpath^^.//*[text()='Search']",
  'surveillance name'=>"xpath^^//*[@id='search_table']/tbody/tr[2]/td[1]/a/span",
  'edit'=>"xpath^^.//*[text()='Edit']",
  'go'=>"xpath^^.//*[text()='Go']",
  'action'=>"xpath^^.//*[@id='navigationAction']",
  'general info'=>"xpath^^.//*[text()='General Info']",
  'additional comments changed'=>"xpath^^//*[@name='additionalComments']",
                        

                   #Surveillance Page objects
                        'surveillance:navigation' => "xpath^^.//*[@id='leftnavmenu']/div[3]/p[11]/a",
                        'reason' => "xpath^^.//*[@name='reason']",
                        'firm lookup' => "xpath^^.//*[contains(text(),'Lookup')]",
                        'tier' => "xpath^^.//*[@name='risk']",
                        'lookup submit' => "xpath^^//*[text()='Submit']",
                        'firm name' => "xpath^^//*[@id='att_container']/div[4]/a[1]/span",
                        'retail project list' => "xpath^^//*[@id='retailProject']",
                        'retail project name' => "xpath^^//*[@id='retailSpecialProject']",

                        # 'food defense tab' => "xpath^^.//*[text()='Food Defense']",
                        'meat' => "xpath^^.//*[@id='meatProducts_checkbox']",
                        'written defence plan' => "xpath^^.//*[@name='writtenFoodDefensePlan']",
                        'coordination activity' => "xpath^^.//*[@id='coordinationActivityDHSCBP_checkbox']",
                        'entry homeland security committees' => "xpath^^//*[@id='homelandSecurityCommittees']",
                        'any activities' => "xpath^^//*[@id='homelandSecurityCommitteesActivities']",
                        'products been held or restricted by cbp' => "xpath^^//*[@id='productsHeldOrRestricted']",
                        'situation and tests conducted' => "xpath^^//*[@id='productsHeldOrRestrictedExplanation']",
                        'outside surveillance system' => "xpath^^.//*[@name='outsideSurveillanceSystem']",
                        'food defense exit notes' => "xpath^^.//*[@name='foodDefenseExitNotes']",
                        'certify checkbox' => "xpath^^.//*[@id='certifiedInfo_checkbox']",

                        # food safety tab
                        'products wholesome' => "xpath^^.//*[@id='productsWholesome']",
                        'sanitary condition ok' => "xpath^^.//*[@id='sanitaryConditionsOK']",
                        'hazard controls adequate' => "xpath^^.//*[@id='hazardControlsAdequate']",
                        'nonhuman food properly denatured' => "xpath^^.//*[@id='nonHumanFoodProperlyDenatured']",
                        'records maintained ok' => "xpath^^.//*[@id='recordsMaintainedOK']",
                        'additional comments1' => "xpath^^.//*[@name='foodSafetyAdditionalComments']",
                        'save food safety' => "xpath^^.//*[contains(text(),'Save Food Safety')]",

                        #Imported Products Tab
                        'handles imported products' => "xpath^^.//*[@id='handlesImpPrd']",
                        'imported products additional comments' => "xpath^^.//*[@name='importedProductsAdditionalComments']",
                        'country of origin' => "xpath^^//*[@id='selectedCountries']",
                        'invoice number' => "xpath^^//*[@id='invoiceNbr']",
                        'bill of landing number' => "xpath^^//*[@id='billofLadingNbr']",
                        'aphis permit number' => "xpath^^//*[@id='aphisPermitNbr']",
                        'hts code' => "xpath^^//*[@id='htsCode']",
                        'custom entry number' => "xpath^^//*[@id='customEntryNbr']",
                        'total cases' => "xpath^^//*[@id='totalCases']",
                        'unit type' => "xpath^^//*[@id='unitType']",
                        'foreign producer foreign establishment number' => "xpath^^//*[@id='foreignProducerEstNbr']",
                        'sample lab form number' => "xpath^^//*[@id='sampleLabFormNbr']",
                        'detained disposition' => "xpath^^//*[@id='detainedDisposition']",
                        'detained disposition details' => "xpath^^//*[@id='detainedDispositionDet']",
                        'recall disposition' => "xpath^^//*[@id='recallDisposition']",
                        'recall disposition details' => "xpath^^//*[@id='recallDispositionDet']",
                        'ftp date initiated' => "xpath^^//*[@name='ftpInitiatedDate']",
                        'ftp disposition' => "xpath^^//*[@id='ftpDisposition']",
                        'ftp disposition details' => "xpath^^//*[@id='ftpDispositionDet']",
                        'oig investigation' => "xpath^^//*[@id='oigInvestigation']",
                        'oig investigation initiated by' => "xpath^^//*[@id='oigInvestigationInitiatedBy']",
                        'oig investigation date' => "xpath^^//*[@name='oigInvestigationDate']",

                        # Additional Info Tab
                        'sample taken' => "xpath^^.//*[@name='sampleTaken']",
                        'selected sample'=> "xpath^^.//*[@id='selectedSamples']",
                        'number of mt samples' => "xpath^^.//*[@id='numMTSamples']",
                        'number of investigative samples' => "xpath^^.//*[@id='numSplProjInvSamples']",
                        'sample result' => "xpath^^.//*[@id='coliSampleResultPositive']",
                        'result of previous sample' => "xpath^^.//*[@id='sampleResultFromPreviousSample']",
                        'date of previous sample' => "xpath^^.//*[@id='previousSampleDate']",
                        'grinding record' => "xpath^^.//*[@id='firmGrindingRec']",
                        'shell egg temperatures' => "xpath^^.//*[@id='shellEggTemp']",
                        'shell eggs properly labeled' => "xpath^^.//*[@id='areShellEggPropMain']",
                        'shell egg temp comments' => "xpath^^.//*[@name='shellEggTempComments']",
                        'pest control visit' => "xpath^^.//*[@id='pestControlVisits']",
                        'frequency of visits' => "xpath^^.//*[@id='frequencyOfVisits']",
                        'pest control contact info' => "xpath^^.//*[@id='pestControlContactInfo']",
                        'investigator meet firm representative' => "xpath^^.//*[@id='investigatorMetWithRepresentative']",
                        'name of representative1' => "xpath^^.//*[@id='representative1']",
                        'name of representative2' => "xpath^^.//*[@id='representative2']",
                        'additional comments' => "xpath^^.//*[@name='additionalInformationAdditionalComments']",
                        'surveillance findings' => "xpath^^.//*[@id='didReferSurvFindings']",
                        'referral comments' => "xpath^^.//*[@name='referralComments']",
                        'surveillance follow up required' => "xpath^^.//*[@id='followUpRequired']",
                        'expected follow up date' => "xpath^^.//*[@id='followUpExpectedDate']",
                        'previous surveillance review' => "xpath^^.//*[@name='followUpFromPrevious']",
                        'follow up comments' => "xpath^^.//*[@id='followUpReason']",

                        # Non Food Safety Consumer Protection Tab
                        'nutritioning label verified' => "xpath^^.//*[@id='nutritionalLblVerify']",
                        'non food safety consumer protection' => "xpath^^.//*[@name='nonFoodSafetyConsumerProtectionOK']",
                        'do records observed' => "xpath^^.//*[@name='doRecordsAsscMeat']",
                        'nonfood safety consumer protection additional comments' => "xpath^^.//*[@id='nonFoodSafetyConsumerProtectionAdditionalComments']",

                        # File Attachments Tab
                        'name to display' => "xpath^^.//*[@id='title']",
                        'browse file' => "xpath^^.//*[@id='attachedFile']",

                        #Associated Product Control Links
                        'product control from date' => "xpath^^.//*[@name='startFromDate']",
                        'product control to date' => "xpath^^.//*[@name='startToDate']",

                        # Order Verification
                        'order verification tab' => "xpath^^.//*[text()='Order Verification']",
                        'compliance with terms and conditions' => "xpath^^.//*[@id='att_container']/div[3]/div[2]/select",
                        'responsible individuals in compliance' => "xpath^^.//*[@id='att_container']/div[4]/div[2]/select",
                        'order verification in additional comments' => "xpath^^.//*[@id='att_container']/textarea",
                        'save order verification' => "xpath^^.//*[text()='Save Order Verification']",
                        'view surveillance' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[16]/a",
                        'custodian name' => "xpath^^//*[@id='search_table']/tbody/tr[2]/td[1]/a/span",
                        'search' => "xpath^^.//*[text()='Search']",
                        'edit' => "xpath^^.//*[text()='Edit']",
                        'go' => "xpath^^.//*[text()='Go']",
                        'shipping access' => "xpath^^.//*[@name='shippingReceivingAccess']",
                        'action' => "xpath^^.//*[@id='navigationAction']",
                        'additional comments changed2' => "xpath^^//*[@name='additionalComments']",
                        'retail project' => "xpath^^.//*[@value='RDCTC']",

                        #Enforcement page objects
                        'misconduct investigation' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[6]/a",
                        'enforcement' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[13]/a",
                        'associated case info tab' => "xpath^^//*[@id='inputForm']/table/tbody/tr/td/ul1]/li2]/a",
                        'associated case info lookup' => "xpath^^//*[@id='att_container']/div[5]/div[2]/a",
                        'lookup search' => "xpath^^//*[@id='search_container']/div[3]/div[2]/a",
                        'investigation file number' => "xpath^^.//*[@name='SearchResultHyperlink']",
                        'primary case type' => "xpath^^.//*[@name='primInvestCaseType']",
                        'primary investigation type' => "xpath^^.//*[@name='primVioType']",
                        'save associated case info' => "xpath^^.//*[text()='Save Associated Case Info']",
                        'enforcement info tab' => "xpath^^.//*[text()='Enforcement Info']",
                        'enforcement case type' => "xpath^^.//*[@name='enforCaseType']",
                        'enforcement violation type' => "xpath^^.//*[@name='enforVioType']",
                        'enforcement status' => "xpath^^.//*[@name='enforStatus']",
                        'primary violator firm name' => "xpath^^.//*[@name='primViolFirmName']",
                        'primary expand' => "xpath^^//*[@id='primSanctionsImage']",
                        'primary felony' => "xpath^^//*[@id='primViolFelonies']",
                        'primary fines' => "xpath^^//*[@id='primViolPenalties']",
                        'secondary expand' => "xpath^^.//*[@id='secSanctionsImage']",
                        'secondary felony' => "xpath^^//*[@id='secViolFelonies']",
                        'secondary fines' => "xpath^^//*[@id='secViolPenalties']",
                        'total felonies' => "xpath^^//*[@id='totfelonies']",
                        'total fines' => "xpath^^//*[@id='totpenalties']",
                        'eld case notes tab' => "xpath^^.//*[text()='ELD Case Notes']",
                        'eld notes' => "xpath^^//*[@id='eedComments']",
                        'eld summary' => "xpath^^//*[@id='actionSummaries']",
                        'additional comments tab' => "xpath^^.//*[text()='Additional Comments']",
                        'additional comments' => "xpath^^//*[@id='additionalComments']",
                        'save additional info' => "xpath^^.//*[text()='Save Additional Info']",
                        'action' => "xpath^^.//*[@id='navigationAction']",
                        'go' => "xpath^^.//*[text()='Go']",
                        'eld specialist' => "xpath^^.//*[@id='navigationAssignee']",
                        'eld specialist go' => "xpath^^//*[@id='EEDAssignmentTxfrRegion3']/a",
                        # 'logout' => "xpath^^//*[@id='leftnavmenu']/div[1]/div[/a/strong",
                        'view enforcement' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[18]/a",
                        'identifier' => "xpath^^//*[@id='action_bar']/div[1]/div[4]",
                        'search' => "xpath^^.//*[text()='Search']",
                        'identifier searchbox' => "xpath^^//*[@id='search_box']/div[2]/div[2]/input",
                        'identifier number' => "xpath^^//*[@id='search_table']/tbody/tr[2]/td[1]/a/span",
                        'eld action1' => "xpath^^//*[@id='eedAction']",
                        'eld date' => "xpath^^//*[@id='eedActionDate']",
                        'ogc action' => "xpath^^//*[@id='ogcAction']",
                        'ogc action date' => "xpath^^//*[@id='ogcActionDate']",
                        'additional comments changed1' => "xpath^^//*[@name='additionalComments']",
                        'region' => "xpath^^//*[@id='navigationRegion']",
                        'region go' => "xpath^^//*[@id='EEDAssignmentTxfrRegion3']/a",
                        'rd action' => "xpath^^//*[@id='rmAction']",
                        'rd action date' => "xpath^^//*[@id='rmActionDate']",
                        'closed date' => "xpath^^//*[@id='closedDate']",
                        'rd view enforcement' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[15]/a",
                   

                    }
end