def map_anetproductcontrol_displayloginaction_do
  @page_objects['anetproductcontrol_displayloginaction_do'] =
      {
          #Login
          'full name' => "css^^.custom-combobox-input.ui-widget.ui-widget-content.ui-state-default.ui-corner-left.ui-autocomplete-input",
          'submit login' => "xpath^^.//*[@type='submit']",
          'role' => "xpath^^//*[@id='change_role_select']",

          #Product Control Page Objects


          'product control' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[10]/a",
          'submit' => "xpath^^//*[text()='Submit']",
          'custodian lookup' => "xpath^^//*[@id='att_container']/div[7]/div[4]/div[3]/span/a",
          'firm identifier' => "xpath^^.//*[@name='firmId']",
          'lookup submit' => "xpath^^//*[text()='Submit']",
          'violator name' => "xpath^^//*[@id='att_container']/div[4]/a[1]/span",
          'save general info' => "xpath^^.//*[text()='Save General Info']",
          'date detained' => "xpath^^//*[@name='startDateND']",
          'extended disposition' => "xpath^^//*[@id='extendedDis']",
          'are owner and custodian the same?' => "xpath^^//*[@id='copyCustodian_checkbox']",
          'product name' => "xpath^^.//*[@id='detain_ProdName']",
          'coding name' => "xpath^^.//*[@id='detain_Coding']",
          'unit type' => "xpath^^.//*[@id='detain_Num']",
          'total number of units' => "xpath^^.//*[@id='detainNumOfUnits']",
          'best buy date' => "xpath^^//*[@id='bestBuyDateText']",
          'production date' => "xpath^^//*[@id='productionDateText']",
          'establishment number' => "xpath^^.//*[@id='detain_EstNum']",
          'location of detained articles' => "xpath^^//*[@id='detain_LocationInfo']",
          'product weight' => "xpath^^//*[@id='productWeightND']",
          'frozen' => "xpath^^//*[@id='detain_Froze_checkbox']",
          'inspection' => "xpath^^//*[@id='detain_Federal_checkbox']",
          'reason' => "xpath^^//*[@id='detain_Misbranded_checkbox']",
          'detained tags' => "xpath^^//*[@id='detain_TagNum']",
          'legal authority for detention' => "xpath^^//*[@id='detain_Act_Poultry_checkbox']",
          'name and address of shipper' => "xpath^^//*[@id='shipperInfo']",
          'name and address of seller' => "xpath^^//*[@id='sellerInfo']",
          'point of shipment (origin)' => "xpath^^//*[@id='pointShipment']",
          'transporter (origin)' => "xpath^^//*[@id='transporter']",
          'was product sampled?' => "xpath^^//*[@id='productSampled']",
          'freezer lot number' => "xpath^^//*[@id='lotNum']",
          'name of owner notified' => "xpath^^//*[@id='nameNotified']",
          'name(s) and address(es) of federal, state, or local authorities notified' => "xpath^^.//*[@id='authoritiesNotifiedInfo']",
          'date owner notified' => "xpath^^//*[@id='dateNotified']",
          'owner informed by' => "xpath^^//*[@id='notifiedBy_TEL_checkbox']",
          'detention code' => "xpath^^.//*[@name='detain_Code']",
          'description' => "xpath^^.//*[@name='detain_ReasonInfo']",
          'voluntary destruction' => "xpath^^//*[@id='voluntaryDestr_checkbox']",
          'destruction date' => "xpath^^//*[@id='voluntaryDestrDate']",
          'placed embargo' => "xpath^^//*[@id='placedEmbargo_checkbox']",
          'embargo description' => "xpath^^//*[@id='placedEmbargoDesc']",
          'product weight ntd' => "xpath^^//*[@name='productWeightNTD']",
          'terminated owner name' => "xpath^^//*[@id='terminate_OwnerNotified']",
          'terminated detained tags' => "xpath^^//*[@id='terminate_SerialNum']",
          'terminated detained date' => "xpath^^//*[@id='terminate_TagDate']",
          'terminated owner notified date' => "xpath^^.//*[@id='terminate_OwnerDate']",
          'terminated owner informed by' => "xpath^^//*[@id='terminateBy_TEL_checkbox']",
          'notice of termination of detention form delivered to' => "xpath^^//*[@id='terminate_DeliveredTo']",
          'ntd remarks' => "xpath^^//*[@id='terminate_RemarksInfo']",
          'date product released' => "xpath^^//*[@id='startDateText']",
          'donation' => "xpath^^//*[@id='useDonation_checkbox']",
          'donation location' => "xpath^^//*[@id='donationLocation']",
          'donation date' => "xpath^^//*[@id='donationDate']",
          'donation organization' => "xpath^^//*[@id='donationOrg']",
          'misbranded by ingredients' => "xpath^^//*[@id='misbrandedByIngred']",
          'misbranded by label information' => "xpath^^//*[@id='misbrandedByLabel']",
          'information description of product' => "xpath^^//*[@id='persDescInfo']",
          'detained' => "xpath^^//*[@id='persDetained_checkbox']",
          'observed on' => "xpath^^//*[@id='persObserved_checkbox']",
          'observed on date' => "xpath^^//*[@id='persObservedDateId']",
          'product weight pun' => "xpath^^//*[@name='productWeightPUN']",
          'owner name pun' => "xpath^^//*[@name='ownerAgentNamePUN']",
          'date product destroyed' => "xpath^^//*[@id='startDateText']",
          'product weight vdhfn' => "xpath^^//*[@name='productWeightVDHFN']",
          'owner name vdhfn' => "xpath^^//*[@name='ownerAgentNameVDHFN']",
          'save voluntay destruction of human food notice' => "xpath^^.//*[text()='Save Voluntary Destruction of Human Food Notice']",
          'associated surveillance links' => "xpath^^.//*[text()='Associated Surveillance Links']",
          # 'add surveillance links' => "xpath^^//*[@id='prdCntrlSurvLinkForm']/div[3]/div[/a",
          'surveillance search' => "xpath^^//*[@id='search_container']/div[3]/div[2]/a",
          'associated investigation links' => "xpath^^.//*[text()='Associated Investigation Links']",
          'add investigation links' => "xpath^^.//*[text()='Add Investigation Link']",
          'investigation file number' => "xpath^^//*[@id='search_table']/tbody/tr[2]/td[1]",
          'view product control' => "xpath^^//*[@id='leftnavmenu']/div[3]/p[15]/a",
          'custodian name' => "xpath^^//*[@id='search_table']/tbody/tr[2]/td[1]/a/span",
          'product control search' => "xpath^^//*[@id='search_container']/font/font/div[/div[2]/a",
          'custodian checkbox' => "xpath^^.//*[@id='copyCustodian_checkbox']",
          'address' => "xpath^^.//*[@name='firmInfo']",
          'mark for deletion' => "xpath^^.//*[@id='markedForRemoval0']",
          'search' => "xpath^^.//*[text()='Search']",
          'surveillance name' => "xpath^^//*[@id='search_table']/tbody/tr[2]/td[1]/a/span",
          'edit' => "xpath^^.//*[text()='Edit']",
          'go' => "xpath^^.//*[text()='Go']",
          'actions' => "xpath^^.//*[@id='navigationAction']",
          'general info' => "xpath^^.//*[text()='General Info']",
          'additional comments changed' => "xpath^^//*[@name='additionalComments']"

      }
end