def map_anetipps_displayloginaction_do
  @page_objects['anetipps_displayloginaction_do'] =
                    {
                        #Login
                        'full name' => "css^^.custom-combobox-input.ui-widget.ui-widget-content.ui-state-default.ui-corner-left.ui-autocomplete-input",
                        'submit login' => "xpath^^.//*[@type='submit']",
                        'role'=>"xpath^^//*[@id='change_role_select']",
                        
                        #IPPS Page Objects


                        'ipps template'=>"xpath^^//*[@id='leftnavmenu']/div[3]/p[19]/a",
  'open template consumer safety inspector'=>"xpath^^//*[@id='search_table']/tbody/tr[2]/td[5]/a/span",
  'open template consumer safety inspector himp'=>"xpath^^//*[@id='search_table']/tbody/tr[3]/td[5]/a/span",
  'open template food inspector eggproducts'=>"xpath^^//*[@id='search_table']/tbody/tr[4]/td[5]/a/span",
  'open template food inspector exports'=>"xpath^^//*[@id='search_table']/tbody/tr[5]/td[5]/a/span",
  'open template food inspector slaughter'=>"xpath^^//*[@id='search_table']/tbody/tr[6]/td[5]/a/span",
  'open template lead consumer safety inspector himp'=>"xpath^^//*[@id='search_table']/tbody/tr[7]/td[5]/a/span",
  'open template public health veterinariana'=>"xpath^^//*[@id='search_table']/tbody/tr[8]/td[5]/a/span",
  'open template public health'=>"xpath^^//*[@id='search_table']/tbody/tr[9]/td[5]/a/span",
  'open template new ipps sample template'=>"xpath^^//*[@id='search_table']/tbody/tr[10]/td[5]/a/span",
  'header'=>"xpath^^.//*[@id='headerName']",
  'subheader'=>"xpath^^.//*[@id='subHeaderName']",
  'section'=>"xpath^^.//*[@id='sectionName']",
  'add element'=>"xpath^^.//*[text()='Add Element']",
  'sequence'=>"xpath^^.//*[@id='elementObject.elementSeqNumTemp']",
  'element'=>"xpath^^//*[@id='elementObject.elementLabelTemp']",
  'save element'=>"xpath^^.//*[contains(text(),'Save Element')]",
  'preview ipps template'=>"xpath^^.//*[contains(text(),'Preview IPPS Template')]",
  'publish ipps template'=>"xpath^^.//*[contains(text(),'Publish IPPS Template')]",
  'create ipps'=>"xpath^^//*[@id='leftnavmenu']/div[3]/p[3]/a",
  'occupation type'=>"xpath^^.//*[@name='assessmentType']",
  'submit'=>"xpath^^.//*[text()='Submit']",
  'employee name'=>"xpath^^.//*[@name='employeeId']",
  'prepare for ipps'=>"xpath^^.//*[@id='prepareIpps']",
  'additional comments'=>"xpath^^.//*[@name='additionalComments']",
  'element satisfactory'=>"xpath^^.//*[@id='elementSatisfactory']",
  'followup'=>"xpath^^.//*[@id='followup']",
  'ipps submit'=>"xpath^^//*[@id='ippsForm']/table[7]/tbody/tr/td[2]/a",
  'assessment number'=>"xpath^^//*[@id='search_table565']/tbody/tr[4]/td[2]",
  'logout'=>"xpath^^//*[@id='leftnavmenu']/div[1]/div/a/strong",
  'supv view ipps'=>"xpath^^//*[@id='leftnavmenu']/div[3]/p[6]/a",
  'fiscal year'=>"xpath^^.//*[@id='fiscalYear']",
  'search'=>"xpath^^//*[@id='search_container']/div[3]/div[2]/a",
  'employee name search'=>"xpath^^/html/body/div/table[2]/tbody/tr[1]/td[2]/table/tbody/tr[2]/td[1]/table[1]/tbody/tr[2]/td[1]/a/span",
  'edit'=>"xpath^^//*[@id='ippsForm']/table[7]/tbody/tr/td[2]/a",
  'supv reviewed'=>"xpath^^//*[@id='ippsForm']/table[7]/tbody/tr[1]/td/input[1]",
  'supv comments'=>"xpath^^//*[@id='ippsForm']/table[7]/tbody/tr[2]/td[1]/textarea",
  'supv submit'=>"xpath^^//*[@id='ippsForm']/table[9]/tbody/tr/td[2]/a",
  'ddm view ipps'=>"xpath^^//*[@id='leftnavmenu']/div[3]/p[10]/a",
  'ddm reviewed'=>"xpath^^//*[@id='ippsForm']/table[9]/tbody/tr[1]/td/input[1]",
  'ddm comments'=>"xpath^^//*[@id='ippsForm']/table[9]/tbody/tr[2]/td[1]/textarea",
  'ddm edit'=>"xpath^^//*[@id='ippsForm']/table[9]/tbody/tr/td[2]/a",
  'earo view ipps'=>"xpath^^//*[@id='leftnavmenu']/div[3]/p[12]/a",
  'earo edit'=>"xpath^^//*[@id='ippsForm']/table[11]/tbody/tr/td[2]/a",
  'earo reviewed'=>"xpath^^//*[@id='ippsForm']/table[11]/tbody/tr[1]/td/input",
  'earo comments'=>"xpath^^//*[@id='ippsForm']/table[11]/tbody/tr[2]/td/textarea",
  'earo submit'=>"xpath^^//*[@id='ippsForm']/table[13]/tbody/tr/td[2]",
  'ddm submit'=>"xpath^^//*[@id='ippsForm']/table[11]/tbody/tr/td[2]/a",
                    }
end