# This file contains page objects xpath for Score case Complainant Type page after Login

def map_score_ccms_case_complainttype
  @page_objects['score_ccms_case_complainttype'] =
      {
          'select complaint type'                   =>    "xpath^^.//*[@id='selectComplaintType']",
          'complaint type:success alert message'    =>    "xpath^^.//*[@id='SuccessAlert']/descendant::*[@id='successAlertText']",
          'complaint type:set primary'              =>    "xpath^^.//*[@id='setPrimaryButton']",
      
      # Page objects for Allergic Reactions page
          'consumer data1:how many people consumed the product?-label'                =>    "xpath^^.//*[@for='AllergicReaction_NumberConsumed']",
          'consumer data1:how many people consumed the product?-field'                =>    "xpath^^.//*[@id='AllergicReaction_NumberConsumed']",
          'consumer data1:how many people experienced a reaction?-label'              =>    "xpath^^.//*[@for='AllergicReaction_NumberPersonsReaction']",
          'consumer data1:how many people experienced a reaction?-field'              =>    "xpath^^.//*[@id='AllergicReaction_NumberPersonsReaction']",
          'consumer data1:what is the age of the person having the reaction?age options-label'    =>    "xpath^^.//*[@for='allergicReactionAgeOptions']",
          'consumer data1:what is the age of the person having the reaction?age options-field'    =>    "xpath^^.//*[@id='allergicReactionAgeOptions']",
          'consumer data1:what is the age of the person having the reaction?age number-field'     =>    "xpath^^.//*[@id='allergicReaction_AgeNumber']",
          'consumer data1:add age'                                                    =>    "xpath^^.//*[@id='addAgeAllergicReaction']",
          'consumer data1:how did consumer prepare the food?-label'                   =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__PreparationMethod']",
          'consumer data1:how did consumer prepare the food?-field'                   =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__PreparationMethod']",
          'consumer data1:how did consumer prepare the food?-characters count'        =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__PreparationMethod']/preceding::span[contains(@class,'maxlength')][1]",
          'consumer data1:has the complainant had a similar reaction before?-label'   =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__SimilarReactionListItemId']",
          'consumer data1:has the complainant had a similar reaction before?-field'   =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__SimilarReactionListItemId']",
          'consumer data1:similar reaction description-label'                         =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__SimilarReactionDescription']",
          'consumer data1:similar reaction description-field'                         =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__SimilarReactionDescription']",
          'consumer data1:similar reaction description:characters count'              =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__SimilarReactionDescription']/preceding::span[contains(@class,'maxlength')][1]",
          'consumer data1:similar reaction description:Error'                         =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__SimilarReactionDescription-error']",
          'consumer data1:additional comments-label'                                  =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__Description']",
          'consumer data1:additional comments-field'                                  =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__Description']",
          'consumer data1:additional comments:characters count'                       =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__Description']/preceding::span[contains(@class,'maxlength')][1]",
          'consumer data1:known allergy/sensitivity-label'                            =>    "xpath^^.//*[@for='allergyOptions0_chosen']",
          'consumer data1:known allergy/sensitivity-field'                            =>    "xpath^^.//*[@id='allergyOptions0']",
          'consumer data1:allergy description-label'                                  =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__AllergyDescription']",
          'consumer data1:allergy description-field'                                  =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__AllergyDescription']",
          'consumer data1:allergy description:characters count'                       =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__AllergyDescription']/preceding::span[contains(@class,'maxlength')][1]",
          'consumer data1:allergy description:error'                                  =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__AllergyDescription-error']",
          'consumer data1:medications given-label'                                    =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__MedicationsGiven']",
          'consumer data1:medications given-field'                                    =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__MedicationsGiven']",
          'consumer data1:medications given:characters count'                         =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__MedicationsGiven']/preceding::span[contains(@class,'maxlength')][1]",
          'consumer data1:medical visit-label'                                        =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__MedicalVisit']",
          'consumer data1:medical visit-field'                                        =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__MedicalVisit']",
          'consumer data1:hospital/clinic name-label'                                 =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__HospitalOrClinicName']",
          'consumer data1:hospital/clinic name-field'                                 =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__HospitalOrClinicName']",
          'consumer data1:hospital/clinic name:characters count'                      =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__HospitalOrClinicName']/preceding::span[contains(@class,'maxlength')][1]",
          'consumer data1:hospital/clinic city-label'                                 =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__HospitalOrClinicCity']",
          'consumer data1:hospital/clinic city-field'                                 =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__HospitalOrClinicCity']",
          'consumer data1:hospital/clinic country-label'                              =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__HospitalCountryId']",
          'consumer data1:hospital/clinic country-field'                              =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__HospitalCountryId']",
          'consumer data1:hospital/clinic state-label'                                =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__HospitalOrClinicState']",
          'consumer data1:hospital/clinic state-field'                                =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__HospitalOrClinicState']",
          'consumer data1:hospital/clinic zip code-label'                             =>    "xpath^^.//*[@for='AllergicReaction_Consumers_0__HospitalOrClinicZip']",
          'consumer data1:hospital/clinic zip code-field'                             =>    "xpath^^.//*[@id='AllergicReaction_Consumers_0__HospitalOrClinicZip']",
          'consumer data:add consumer'                                                =>    "xpath^^.//*[@id='allergicReactionAddConsumer']",
          'consumer data:save'                                                        =>    "xpath^^.//*[@id='allergicReactionSave']",
          'consumer data:cancel'                                                      =>    "xpath^^.//*[@id='allergicReactionCancel']",

      # Page Objects for Create Case> Complaint Type> Economic Adulteration page
        'economic adulteration:concern'                                   =>    "xpath^^.//*[@id='EconomicAdulterationConcern']",
        'economic adulteration:concern:error'                             =>    "xpath^^.//*[@id='EconomicAdulterationConcern-error']",
        'economic adulteration:additional description'                    =>    "xpath^^.//*[@id='EconomicAdulterationDescription']",
        'economic adulteration:additional description:error'              =>    "xpath^^.//*[@id='EconomicAdulterationDescription-error']",
        'economic adulteration:additional description:characters count'   =>    "xpath^^.//*[@id='EconomicAdulterationDescription']/following::span[contains(@class,'maxlength')][1]",
        'economic adulteration:save'                                      =>    "xpath^^.//*[@id='economicAdulterationSave']",
        'economic adulteration:cancel'                                    =>    "xpath^^.//*[@id='economicAdulterationCancel']",

  # Page Objects for Create Case> Complaint Type> Off Taste /Off Odor / Off appearance page
    'off taste odor appearance:off taste'                                 =>      "xpath^^.//*[@id='IsOffTaste']",
    'off taste odor appearance:off taste list'                            =>      "xpath^^.//*[@id='OffTasteListItems']",
    'off taste odor appearance:off taste description'                     =>      "xpath^^.//*[@id='OffTasteDescription']",
    'off taste odor appearance:off taste description:characters count'    =>      "xpath^^.//*[@id='OffTasteDescription']/following::span[contains(@class,'maxlength')][1]",
    'off taste odor appearance:off taste description:error'               =>      "xpath^^.//*[@id='OffTasteDescription-error']",
    'off taste odor appearance:off odor'                                  =>      "xpath^^.//*[@id='IsOffOdor']",
    'off taste odor appearance:off odor list'                             =>      "xpath^^.//*[@id='OffOdorListItems']",
    'off taste odor appearance:off odor description'                      =>      "xpath^^.//*[@id='OffOdorDescription']",
    'off taste odor appearance:off odor description:characters count'     =>      "xpath^^.//*[@id='OffOdorDescription']/following::span[contains(@class,'maxlength')][1]",
    'off taste odor appearance:off odor description:error'                =>      "xpath^^.//*[@id='OffOdorDescription-error']",
    'off taste odor appearance:off appearance'                            =>      "xpath^^.//*[@id='IsOffAppearance']",
    'off taste odor appearance:off appearance list'                       =>      "xpath^^.//*[@id='OffAppearanceListItems']",
    'off taste odor appearance:off appearance description'                =>      "xpath^^.//*[@id='OffAppearanceDescription']",
    'off taste odor appearance:off appearance description:characters count'   =>      "xpath^^.//*[@id='OffAppearanceDescription']/following::span[contains(@class,'maxlength')][1]",
    'off taste odor appearance:off appearance description:error'          =>      "xpath^^.//*[@id='OffAppearanceDescription-error']",
    'off taste odor appearance:save'                                      =>      "xpath^^.//*[@id='offTasteOdorAppearanceSave']",
    'off taste odor appearance:cancel'                                    =>      "xpath^^.//*[@id='offTasteOdorAppearanceCancel']",


  # Page Objects for Create Case> Complaint Type> Other (Non-Specific) page

    'other:concern-label'                                   =>      "xpath^^.//*[@for='OtherComplaint_Concern']",
    'other:concern-field'                                   =>      "xpath^^.//*[@id='OtherComplaintTypeConcernDropDown']",
    'other:concern-error'                                   =>      "xpath^^.//*[@id='OtherComplaintTypeConcernDropDown-error']",
    'other:additional description-label'                    =>      "xpath^^.//*[@for='OtherComplaintTypeDescription']",
    'other:additional description-field'                    =>      "xpath^^.//*[@id='OtherComplaintTypeDescription']",
    'other:additional description-characters count'         =>      "xpath^^.//*[@id='OtherComplaintTypeDescription']/following::span[contains(@class,'maxlength')][1]",
    'other:additional description-error'                    =>      "xpath^^.//*[@id='OtherComplaintTypeDescription-error']",
    'other:save'                                            =>      "xpath^^.//*[@id='otherSave']",
    'other:cancel'                                          =>      "xpath^^.//*[@id='otherCancel']",

  # Page Objects for Create Case> Complaint Type> Misbranding/Mislabeling page

    'misbranding/mislabeled:alleged issue-label'            =>      "xpath^^.//*[@for='MisbrandingConcern']",
    'misbranding/mislabeled:alleged issue-field'            =>      "xpath^^.//*[@id='MisbrandingConcern']",
    'misbranding/mislabeled:additional description-label'   =>      "xpath^^.//*[@for='MisbrandingDescription']",
    'misbranding/mislabeled:additional description-field'   =>      "xpath^^.//*[@id='MisbrandingDescription']",
    'misbranding/mislabeled:additional description-characters count'  =>      "xpath^^.//*[@id='MisbrandingDescription']/following::span[contains(@class,'maxlength')][1]",
    'misbranding/mislabeled:additional description-error'   =>      "xpath^^.//*[@id='MisbrandingDescription-error']",
    'misbranding/mislabeled:save'                           =>      "xpath^^.//*[@id='misbrandingSave']",
    'misbranding/mislabeled:cancel'                         =>      "xpath^^.//*[@id='misbrandingCancel']",


  # Page Objects for Create Case> Complaint Type> Injury page

    'injury:success alert message'                        =>      "xpath^^.//*[@id='injuryFormError']/descendant::*[@id='successAlertText']",
    'injury:table header-type of injury-label'            =>      "xpath^^.//*[@id='injury-type-table']/descendant::th[1]",
    'injury:table header-how soon after eating did the injury occur?-label'     =>      "xpath^^.//*[@id='injury-type-table']/descendant::th[2]",
    'injury:table header-description-label'               =>      "xpath^^.//*[@id='injury-type-table']/descendant::th[3]",
    'injury:burn-label'                                   =>      "xpath^^.//*[@id='injury-type-table']/tbody/tr[1]/td[1]",
    'injury:burn:how soon after eating did the injury occur?-field'     =>      "xpath^^.//*[@id='InjuryTimeFirst']",
    'injury:burn:description-field'      => "xpath^^.//*[@id='InjuryTimeFirstDescription']",
    'injury:broken/loose tooth-label'                     =>      "xpath^^.//*[@id='injury-type-table']/tbody/tr[2]/td[1]",
    'injury:broken/loose tooth:how soon after eating did the injury occur?-field'     =>      "xpath^^.//*[@id='InjuryTimeSecond']",
    'injury:broken/loose tooth:description-field'         =>      "xpath^^.//*[@id='InjuryTimeSecondDescription']",
    'injury:choking-label'                                =>      "xpath^^.//*[@id='injury-type-table']/tbody/tr[3]/td[1]",
    'injury:choking:how soon after eating did the injury occur?-field'    =>      "xpath^^.//*[@id='InjuryTimeThird']",
    'injury:choking:description-field'                    =>      "xpath^^.//*[@id='InjuryTimeThirdDescription']",
    'injury:laceration-label'                             =>      "xpath^^.//*[@id='injury-type-table']/tbody/tr[4]/td[1]",
    'injury:laceration:how soon after eating did the injury occur?-field'   =>      "xpath^^.//*[@id='InjuryTimeFourth']",
    'injury:laceration:description-field'                 =>      "xpath^^.//*[@id='InjuryTimeFourthDescription']",
    'injury:toothache-label'                              =>      "xpath^^.//*[@id='injury-type-table']/tbody/tr[5]/td[1]",
    'injury:toothache:how soon after eating did the injury occur?-field'    =>      "xpath^^.//*[@id='InjuryTimeFifth']",
    'injury:toothache:description-field'                  =>      "xpath^^.//*[@id='InjuryTimeFifthDescription']",
    'injury:other-label'                                  =>      "xpath^^.//*[@id='injury-type-table']/tbody/tr[6]/td[1]",
    'injury:other:how soon after eating did the injury occur?-field'    =>      "xpath^^.//*[@id='InjuryTimeSixth']",
    'injury:other:description-field'                      =>      "xpath^^.//*[@id='InjuryTimeSixthDescription']",
    'injury:other:description-error'                      =>      "xpath^^.//*[@id='InjuryTimeSixthDescription-error']",
    'injury:medical visit-label'                          =>      "xpath^^.//*[@for='InjuryMedicalVisit']",
    'injury:medical visit-field'                          =>      "xpath^^.//*[@id='InjuryMedicalVisit']",
    'injury:hospital/clinic name-label'                   =>      "xpath^^.//*[@for='InjuryHospitalName']",
    'injury:hospital/clinic name-field'                   =>      "xpath^^.//*[@id='InjuryHospitalName']",
    'injury:hospital/clinic city-label'                   =>      "xpath^^.//*[@for='InjuryHospitalCity']",
    'injury:hospital/clinic city-field'                   =>      "xpath^^.//*[@id='InjuryHospitalCity']",
    'injury:hospital/clinic country-label'                =>      "xpath^^.//*[@for='InjuryHospitalCountry']",
    'injury:hospital/clinic country-field'                =>      "xpath^^.//*[@id='InjuryHospitalCountry']",
    'injury:hospital/clinic state-label'                  =>      "xpath^^.//*[@for='InjuryHospitalStateId']",
    'injury:hospital/clinic state-field'                  =>      "xpath^^.//*[@id='InjuryHospitalStateId']",
    'injury:hospital/clinic zip-label'                    =>      "xpath^^.//*[@for='InjuryHospitalZip']",
    'injury:hospital/clinic zip-field'                    =>      "xpath^^.//*[@id='InjuryHospitalZip']",
    'injury:additional description-label'                 =>      "xpath^^.//*[@for='InjuryDescription']",
    'injury:additional description-field'                 =>      "xpath^^.//*[@id='InjuryDescription']",
    'injury:additional description-characters count'      =>      "xpath^^.//*[@id='InjuryDescription']/following::span[contains(@class,'maxlength')][1]",
    'injury:save'                                         =>      "xpath^^.//*[@id='injurySave']",
    'injury:cancel'                                       =>      "xpath^^.//*[@id='injuryCancel']",


  # Page Objects for Create Case> Complaint Type> Illness page
    'illness:consumer data1:how many people consumed the product?-label'          =>      "xpath^^.//*[@for='Illness_NumberConsumed']",
    'illness:consumer data1:how many people consumed the product?-field'          =>      "xpath^^.//*[@id='Illness_NumberConsumed']",
    # 'illness:consumer data1:how many people consumed the product?:error'=>      "xpath^^"
    'illness:consumer data1:how many people became ill?-label'                    =>      "xpath^^.//*[@for='Illness_NumberPersonsIll']",
    'illness:consumer data1:how many people became ill?-field'                    =>      "xpath^^.//*[@id='Illness_NumberPersonsIll']",
    'illness:consumer data1:how many people became ill?:error'                    =>      "xpath^^.//*[@id='Illness_NumberPersonsIll-error']",
    'illness:consumer data1:what is the age(s) of the person(s) having the reaction?-label'   =>      "xpath^^.//*[@for='illnessAgeOptions']",
    'illness:consumer data1:age of ill person years-field'                        =>      "xpath^^.//*[@id='illnessAgeOptions']",
    'illness:consumer data1:age of ill person age number-field'                   =>      "xpath^^.//*[@id='illness_AgeNumber']",
    'illness:consumer data1:add age'                                              =>      "xpath^^.//*[@id='addAges']",
    'illness:consumer data1:72 hour food history-label'                           =>      "xpath^^.//*[@id='addAges']/following::div[contains(text(),'72 Hour Food History')]",
    'illness:consumer data1:72-hours history:breakfast-label'                     =>      "xpath^^.//*[@for='Illness_Consumers_0__FoodHistoryBreakfast']",
    'illness:consumer data1:72-hours history:breakfast-field'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__FoodHistoryBreakfast']",
    'illness:consumer data1:72-hours history:breakfast-character count'           =>      "xpath^^.//*[@id='Illness_Consumers_0__FoodHistoryBreakfast']/following::span[contains(@class,'maxlength')][1]",
    'illness:consumer data1:72-hours history:lunch-label'                         =>      "xpath^^//*[@for='Illness_Consumers_0__FoodHistoryLunch']",
    'illness:consumer data1:72-hours history:lunch-field'                         =>      "xpath^^//*[@id='Illness_Consumers_0__FoodHistoryLunch']",
    'illness:consumer data1:72-hours history:lunch-character count'               =>      "xpath^^//*[@id='Illness_Consumers_0__FoodHistoryLunch']/following::span[contains(@class,'maxlength')][1]",
    'illness:consumer data1:72-hours history:dinner-label'                        =>      "xpath^^//*[@for='Illness_Consumers_0__FoodHistoryDinner']",
    'illness:consumer data1:72-hours history:dinner-field'                        =>      "xpath^^//*[@id='Illness_Consumers_0__FoodHistoryDinner']",
    'illness:consumer data1:72-hours history:dinner-character count'              =>      "xpath^^//*[@id='Illness_Consumers_0__FoodHistoryDinner']/following::span[contains(@class,'maxlength')][1]",
    'illness:consumer data1:72-hours history:snack-label'                         =>      "xpath^^//*[@for='Illness_Consumers_0__FoodHistorySnack']",
    'illness:consumer data1:72-hours history:snack-field'                         =>      "xpath^^//*[@id='Illness_Consumers_0__FoodHistorySnack']",
    'illness:consumer data1:72-hours history:snack-character count'               =>      "xpath^^//*[@id='Illness_Consumers_0__FoodHistorySnack']/following::span[contains(@class,'maxlength')][1]",
    'illness:consumer data1:recent travel-label'                                  =>      "xpath^^.//*[contains(text(),'Recent Travel')]",
    'illness:consumer data1:recent travel1:travel type-label'                     =>      "xpath^^.//*[@for='Illness_Consumers_0__TravelTypeListItemIdFirst']",
    'illness:consumer data1:recent travel1:travel type-field'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__TravelTypeListItemIdFirst']",
    'illness:consumer data1:recent travel1:state-label'                           =>      "xpath^^.//*[@for='Illness_Consumers_0__StateListItemIdFirst']",
    'illness:consumer data1:recent travel1:state-field'                           =>      "xpath^^.//*[@id='Illness_Consumers_0__StateListItemIdFirst']",
    'illness:consumer data1:recent travel1:country-field'                         =>      "xpath^^.//*[@id='Illness_Consumers_0__CountryListItemIdFirst']",
    'illness:consumer data1:recent travel1:travel date-label'                     =>      "xpath^^.//*[@for='Illness_Consumers_0__TravelDateFirst']",
    'illness:consumer data1:recent travel1:travel date-field'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__TravelDateFirst']",
    'illness:consumer data1:recent travel1:travel date:error'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__TravelDateFirst-error']",
    'illness:consumer data1:recent travel2:travel type-label'                     =>      "xpath^^.//*[@for='Illness_Consumers_0__TravelTypeListItemIdSecond']",
    'illness:consumer data1:recent travel2:travel type-field'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__TravelTypeListItemIdSecond']",
    'illness:consumer data1:recent travel2:state-label'                           =>      "xpath^^.//*[@for='Illness_Consumers_0__StateListItemIdSecond']",
    'illness:consumer data1:recent travel2:state-field'                           =>      "xpath^^.//*[@id='Illness_Consumers_0__StateListItemIdSecond']",
    'illness:consumer data1:recent travel2:country-field'                         =>      "xpath^^.//*[@id='Illness_Consumers_0__CountryListItemIdSecond']",
    'illness:consumer data1:recent travel2:travel date-label'                     =>      "xpath^^.//*[@for='Illness_Consumers_0__TravelDateSecond']",
    'illness:consumer data1:recent travel2:travel date-field'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__TravelDateSecond']",
    'illness:consumer data1:recent travel2:travel date:error'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__TravelDateSecond-error']",
    'illness:consumer data1:recent travel3:travel type-label'                     =>      "xpath^^.//*[@for='Illness_Consumers_0__TravelTypeListItemIdThird']",
    'illness:consumer data1:recent travel3:travel type-field'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__TravelTypeListItemIdThird']",
    'illness:consumer data1:recent travel3:state-label'                           =>      "xpath^^.//*[@for='Illness_Consumers_0__StateListItemIdThird']",
    'illness:consumer data1:recent travel3:state-field'                           =>      "xpath^^.//*[@id='Illness_Consumers_0__StateListItemIdThird']",
    'illness:consumer data1:recent travel3:country-field'                         =>      "xpath^^.//*[@id='Illness_Consumers_0__CountryListItemIdThird']",
    'illness:consumer data1:recent travel3:travel date-label'                     =>      "xpath^^.//*[@for='Illness_Consumers_0__TravelDateThird']",
    'illness:consumer data1:recent travel3:travel date-field'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__TravelDateThird']",
    'illness:consumer data1:recent travel3:travel date:error'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__TravelDateThird-error']",
    'illness:consumer data1:medical visit-label'                                  =>      "xpath^^.//*[@for='Illness_Consumers_0__MedicalVisit']",
    'illness:consumer data1:medical visit-field'                                  =>      "xpath^^.//*[@id='Illness_Consumers_0__MedicalVisit']",
    'illness:consumer data1:hospital/clinic name-label'                           =>      "xpath^^.//*[@for='Illness_Consumers_0__HospitalName']",
    'illness:consumer data1:hospital/clinic name-field'                           =>      "xpath^^.//*[@id='Illness_Consumers_0__HospitalName']",
    'illness:consumer data1:hospital/clinic city-label'                           =>      "xpath^^.//*[@for='Illness_Consumers_0__HospitalCity']",
    'illness:consumer data1:hospital/clinic city-field'                           =>      "xpath^^.//*[@id='Illness_Consumers_0__HospitalCity']",
    'illness:consumer data1:hospital/clinic state-label'                          =>      "xpath^^.//*[@for='Illness_Consumers_0__HospitalStateListItemId']",
    'illness:consumer data1:hospital/clinic state-field'                          =>      "xpath^^.//*[@id='Illness_Consumers_0__HospitalStateListItemId']",
    'illness:consumer data1:hospital/clinic zip code-label'                       =>      "xpath^^.//*[@for='Illness_Consumers_0__HospitalZip']",
    'illness:consumer data1:hospital/clinic zip code-field'                       =>      "xpath^^.//*[@id='Illness_Consumers_0__HospitalZip']",
    'illness:consumer data1:hospital/clinic country-label'                        =>      "xpath^^.//*[@for='Illness_Consumers_0__HospitalCountryListItemId']",
    'illness:consumer data1:hospital/clinic country-field'                        =>      "xpath^^.//*[@id='Illness_Consumers_0__HospitalCountryListItemId']",
    'illness:consumer data1:medical diagnosis-label'                              =>      "xpath^^.//*[@id='tabs-illness']/descendant::*[contains(text(),'Medical Diagnosis')][1]",
    'illness:consumer data1:medical diagnosis:unknown-label'                      =>      "xpath^^.//*[@for='Illness_Consumers_0__IsUnknown']",
    'illness:consumer data1:medical diagnosis:unknown-field'                      =>      "xpath^^.//*[@id='Illness_Consumers_0__IsUnknown']",
    'illness:consumer data1:medical diagnosis:pathogen/parasite-label'            =>      "xpath^^.//*[@for='Illness_Consumers_0__IsPathogen']",
    'illness:consumer data1:medical diagnosis:pathogen/parasite-field'            =>      "xpath^^.//*[@id='Illness_Consumers_0__IsPathogen']",
    'illness:consumer data1:medical diagnosis:pathogen/parasite dropdown-field'   =>      "xpath^^.//*[@id='Illness_Consumers_0__PathogenListItemId']",
    'illness:consumer data1:medical diagnosis:chemical-label'                     =>      "xpath^^.//*[@for='Illness_Consumers_0__IsChemical']",
    'illness:consumer data1:medical diagnosis:chemical-field'                     =>      "xpath^^.//*[@id='Illness_Consumers_0__IsChemical']",
    'illness:consumer data1:medical diagnosis:chemical dropdown-field'            =>      "xpath^^.//*[@id='Illness_Consumers_0__ChemicalListItemId']",
    'illness:consumer data1:medical diagnosis:pathogen/parasite:lab confirmed?-label'   =>      "xpath^^.//*[@for='Illness_Consumers_0__PathogenLabConfirmedListItemId']",
    'illness:consumer data1:medical diagnosis:pathogen/parasite:lab confirmed?-field'   =>      "xpath^^.//*[@id='Illness_Consumers_0__PathogenLabConfirmedListItemId']",
    'illness:consumer data1:medical diagnosis:chemical:lab confirmed?-label'            =>      "xpath^^.//*[@for='Illness_Consumers_0__ChemicalLabConfirmedListItemId']",
    'illness:consumer data1:medical diagnosis:chemical:lab confirmed?-field'            =>      "xpath^^.//*[@id='Illness_Consumers_0__ChemicalLabConfirmedListItemId']",
    'illness:consumer data1:medical diagnosis:pathogen/parasite:other comments-label'   =>      "xpath^^.//*[@for='Illness_Consumers_0__PathogenOtherComments']",
    'illness:consumer data1:medical diagnosis:pathogen/parasite:other comments-field'   =>      "xpath^^.//*[@id='Illness_Consumers_0__PathogenOtherComments']",
    'illness:consumer data1:medical diagnosis:pathogen/parasite:other comments-error'   =>      "xpath^^.//*[@id='Illness_Consumers_0__PathogenOtherComments-error']",
    'illness:consumer data1:medical diagnosis:chemical:other comments-label'            =>      "xpath^^.//*[@for='Illness_Consumers_0__ChemicalOtherComments']",
    'illness:consumer data1:medical diagnosis:chemical:other comments-field'            =>      "xpath^^.//*[@id='Illness_Consumers_0__ChemicalOtherComments']",
    'illness:consumer data1:medical diagnosis:chemical:other comments-error'            =>      "xpath^^.//*[@id='Illness_Consumers_0__ChemicalOtherComments-error']",
    'illness:consumer data1:medications given-label'                                    =>      "xpath^^.//*[@for='Illness_Consumers_0__MedicationsGiven']",
    'illness:consumer data1:medications given-field'                                    =>      "xpath^^.//*[@id='Illness_Consumers_0__MedicationsGiven']",
    'illness:consumer data1:add additional contacts info-label'                         =>      "xpath^^.//*[@for='Illness_Consumers_0__AdditionalContactInformationListItemId']",
    'illness:consumer data1:add additional contacts info-field'                         =>      "xpath^^.//*[@id='Illness_Consumers_0__AdditionalContactInformationListItemId']",
    'illness:consumer data:add consumer'                                                =>      "xpath^^.//*[@id='illnessAddConsumer']",
    'illness:consumer data::save'                                                       =>      "xpath^^.//*[@id='illnessSave']",
    'illness:consumer data::cancel'                                                     =>      "xpath^^.//*[@id='illnessCancel']"

  }
end