# This file contains page objects xpath for Score case contacts page after Login
def map_score_ccms_case_casecontacts
  @page_objects['score_ccms_case_casecontacts'] =
      {
          'case contacts:success alert'                     =>      "xpath^^.//*[@id='successAlertText-CaseContact']",
          'case contacts:add contacts'                      =>      "xpath^^.//*[@id='add-case-contact-button']",
          'case contacts:complainant accordion name'        =>      "xpath^^.//*[@id='accordion-button-contact-4']",
          'case contacts:complainant save'                  =>      "xpath^^.//*[@id='save-contact-form-4']",
          'case contacts:complainant edit'                  =>      "xpath^^.//*[@id='edit-contact-form-4']",
          'case contacts:complainant information icon'      =>      "xpath^^.//*[@class='fas fa-info-circle fa-2x blue']",
          'case contacts:complainant first name'            =>      "xpath^^.//*[@id='TransitoryContactsTabContact_FirstName']",
          'case contacts:complainant last name'             =>      "xpath^^.//*[@id='TransitoryContactsTabContact_LastName']",
          'case contacts:complainant relation to case'      =>      "xpath^^.//*[@id='TransitoryContactsTabContact_RelationToCaseId']",
          'case contacts:complainant company name'          =>      "xpath^^.//*[@id='TransitoryContactsTabContact_CompanyName']",
          'case contacts:complainant address line 1'        =>      "xpath^^.//*[@id='TransitoryContactsTabContact_AddressLineOne']",
          'case contacts:complainant address line 2'        =>      "xpath^^.//*[@id='TransitoryContactsTabContact_AddressLineTwo']",
          'case contacts:complainant city'                  =>      "xpath^^.//*[@id='TransitoryContactsTabContact_City']",
          'case contacts:complainant country'               =>      "xpath^^.//*[@id='TransitoryContactsTabContact_CountryId']",
          'case contacts:complainant state'                 =>      "xpath^^.//*[@id='TransitoryContactsTabContact_StateName']",
          'case contacts:complainant usstate'                 =>      "xpath^^.//*[@id='TransitoryContactsTabContact_StateId']",
          'case contacts:complainant zip code'              =>      "xpath^^.//*[@id='TransitoryContactsTabContact_Zip']",
          'case contacts:complainant1 accordion name'       =>      "xpath^^.//*[@id='accordion-button-contact-3']",
          'case contacts:complainant1 first name'           =>      "xpath^^.//*[@id='Case_Contacts_3__FirstName']",
          'case contacts:complainant1 last name'            =>      "xpath^^.//*[@id='Case_Contacts_3__LastName']",
          'case contacts:complainant1 relation to case'     =>      "xpath^^.//*[@id='Case_Contacts_3__RelationToCaseId']",
          'case contacts:complainant1 company name'         =>      "xpath^^.//*[@id='Case_Contacts_3__CompanyName']",
          'case contacts:complainant1 address line 1'       =>      "xpath^^.//*[@id='Case_Contacts_3__AddressLineOne']",
          'case contacts:complainant1 address line 2'       =>      "xpath^^.//*[@id='Case_Contacts_3__AddressLineTwo']",
          'case contacts:complainant1 city'                 =>      "xpath^^.//*[@id='Case_Contacts_3__City']",
          'case contacts:complainant1 country'              =>      "xpath^^.//*[@id='Case_Contacts_3__CountryId']",
          'case contacts:complainant1 state'                =>      "xpath^^.//*[@id='Case_Contacts_3__StateId']",
          'case contacts:complainant1 edit state'           =>      "xpath^^//*[@id='Case_Contacts_3__StateName']",
          'case contacts:complainant1 zip code'             =>      "xpath^^.//*[@id='Case_Contacts_3__Zip']",
          'case contacts:complainant1 edit'                 =>      "xpath^^.//*[@id='edit-contact-form-3']",
          'case contacts:complainant1 save'                 =>      "xpath^^.//*[@id='save-contact-form-3']",
          'case contacts:complainant1 cancel'               =>      "xpath^^.//*[@id='delete-contact-form-3']",
          'case contacts:complainant1 delete'               =>      "xpath^^.//*[@id='delete-contact-form-3']",
          'case contacts:complainant data1:add contact type'  =>      "xpath^^.//*[@id='accordion-button-contact-3']/following-sibling::div/descendant::button[contains(text(),'Add Contact Details')]",
          'case contacts:complainant2 accordion name'       =>      "xpath^^.//*[@id='accordion-button-contact-2']",
          'case contacts:complainant2 first name'           =>      "xpath^^.//*[@id='Case_Contacts_2__FirstName']",
          'case contacts:complainant2 last name'            =>      "xpath^^.//*[@id='Case_Contacts_2__LastName']",
          'case contacts:complainant2 relation to case'     =>      "xpath^^.//*[@id='Case_Contacts_2__RelationToCaseId']",
          'case contacts:complainant2 company name'         =>      "xpath^^.//*[@id='Case_Contacts_2__CompanyName']",
          'case contacts:complainant2 address line 1'       =>      "xpath^^.//*[@id='Case_Contacts_2__AddressLineOne']",
          'case contacts:complainant2 address line 2'       =>      "xpath^^.//*[@id='Case_Contacts_2__AddressLineTwo']",
          'case contacts:complainant2 city'                 =>      "xpath^^.//*[@id='Case_Contacts_2__City']",
          'case contacts:complainant2 country'              =>      "xpath^^.//*[@id='Case_Contacts_2__CountryId']",
          'case contacts:complainant2 state'                =>      "xpath^^.//*[@id='Case_Contacts_2__StateId']",
          'case contacts:complainant2 zip code'             =>      "xpath^^.//*[@id='Case_Contacts_2__Zip']",
          'case contacts:complainant2 edit'                 =>      "xpath^^.//*[@id='edit-contact-form-2']",
          'case contacts:complainant2 save'                 =>      "xpath^^.//*[@id='save-contact-form-2']",
          'case contacts:complainant2 cancel'               =>      "xpath^^.//*[@id='delete-contact-form-2']",
          'case contacts:complainant2 delete'               =>      "xpath^^.//*[@id='delete-contact-form-2']",
          'case contacts:complainant data2:add contact type'  =>      "xpath^^.//*[@id='accordion-button-contact-2']/following-sibling::div/descendant::button[contains(text(),'Add Contact Details')]",
          'case contacts:complainant3 accordion name'       =>      "xpath^^.//*[@id='accordion-button-contact-1']",
          'case contacts:complainant3 first name'           =>      "xpath^^.//*[@id='Case_Contacts_1__FirstName']",
          'case contacts:complainant3 last name'            =>      "xpath^^.//*[@id='Case_Contacts_1__LastName']",
          'case contacts:complainant3 relation to case'     =>      "xpath^^.//*[@id='Case_Contacts_1__RelationToCaseId']",
          'case contacts:complainant3 company name'         =>      "xpath^^.//*[@id='Case_Contacts_1__CompanyName']",
          'case contacts:complainant3 address line 1'       =>      "xpath^^.//*[@id='Case_Contacts_1__AddressLineOne']",
          'case contacts:complainant3 address line 2'       =>      "xpath^^.//*[@id='Case_Contacts_1__AddressLineTwo']",
          'case contacts:complainant3 city'                 =>      "xpath^^.//*[@id='Case_Contacts_1__City']",
          'case contacts:complainant3 country'              =>      "xpath^^.//*[@id='Case_Contacts_1__CountryId']",
          'case contacts:complainant3 state'                =>      "xpath^^.//*[@id='Case_Contacts_1__StateId']",
          'case contacts:complainant3 zip code'             =>      "xpath^^.//*[@id='Case_Contacts_1__Zip']",
          'case contacts:complainant3 edit'                 =>      "xpath^^.//*[@id='edit-contact-form-1']",
          'case contacts:complainant3 save'                 =>      "xpath^^.//*[@id='save-contact-form-1']",
          'case contacts:complainant3 cancel'               =>      "xpath^^.//*[@id='delete-contact-form-1']",
          'case contacts:complainant3 delete'               =>      "xpath^^.//*[@id='delete-contact-form-1']",
          'case contacts:complainant data3:add contact type'  =>      "xpath^^.//*[@id='accordion-button-contact-1']/following-sibling::div/descendant::button[contains(text(),'Add Contact Details')]",
          'case contacts:complainant4 accordion name'       =>      "xpath^^.//*[@id='accordion-button-contact-0']",
          'case contacts:complainant4 first name'           =>      "xpath^^.//*[@id='Case_Contacts_0__FirstName']",
          'case contacts:complainant4 last name'            =>      "xpath^^.//*[@id='Case_Contacts_0__LastName']",
          'case contacts:complainant4 relation to case'     =>      "xpath^^.//*[@id='Case_Contacts_0__RelationToCaseId']",
          'case contacts:complainant4 company name'         =>      "xpath^^.//*[@id='Case_Contacts_0__CompanyName']",
          'case contacts:complainant4 address line 1'       =>      "xpath^^.//*[@id='Case_Contacts_0__AddressLineOne']",
          'case contacts:complainant4 address line 2'       =>      "xpath^^.//*[@id='Case_Contacts_0__AddressLineTwo']",
          'case contacts:complainant4 city'                 =>      "xpath^^.//*[@id='Case_Contacts_0__City']",
          'case contacts:complainant4 country'              =>      "xpath^^.//*[@id='Case_Contacts_0__CountryId']",
          'case contacts:complainant4 state'                =>      "xpath^^.//*[@id='Case_Contacts_0__StateId']",
          'case contacts:complainant4 zip code'             =>      "xpath^^.//*[@id='Case_Contacts_0__Zip']",
          'case contacts:complainant4 edit'                 =>      "xpath^^.//*[@id='edit-contact-form-0']",
          'case contacts:complainant4 save'                 =>      "xpath^^.//*[@id='save-contact-form-0']",
          'case contacts:complainant4 cancel'               =>      "xpath^^.//*[@id='delete-contact-form-0']",
          'case contacts:complainant4 delete'               =>      "xpath^^.//*[@id='delete-contact-form-0']",
          'case contacts:complainant data4:add contact type'  =>      "xpath^^.//*[@id='accordion-button-contact-0']/following-sibling::div/descendant::button[contains(text(),'Add Contact Details')]",
          # Add Contact
          'case contacts:contact type'                      =>      "xpath^^.//*[@id='Contact_Options']",
          'case contacts:add contact details'               =>      "xpath^^.//*[@id='Contact_Details']",
          'case contacts:add contact:add'                   =>      "xpath^^.//*[@id='Contact_Add']"
      }
end