# This file contains page objects xpath for Score case Complainant Data page after Login

def map_score_ccms_case_complainantdata
  @page_objects['score_ccms_case_complainantdata'] =
      {
          'case details header'                       =>   "xpath^^.//*[@id='form-actions']/h2",
          'complaint data: disclaimer message'        =>   "xpath^^.//div[@class='information-width-one-whole'][1]",
          'incident date:-label'                      =>   "xpath^^.//*[@for='Case_DateOfIncident']",
          'incident date:'                            =>   "xpath^^.//*[@id='Case_DateOfIncident']",
          'incident date:calendar'                    =>   "xpath^^.//*[@id='Case_DateOfIncident']/following::img[@alt='Select date'][1]",
          'report death'                              =>   "xpath^^.//label[text() = 'Report Death']/preceding::input[2]",
          'complaint description'                     =>   "xpath^^.//*[@id='Case_OriginalStatement']",
          'complaint description:characters count'    =>   "xpath^^.//*[@id='Case_OriginalStatement']/following::span[contains(@class,'maxlength')][1]",
          'complaint description:error message'       =>   "xpath^^.//*[@id='Case_OriginalStatement-error']",
          'anonymous complainant'                     =>    "xpath^^.//*[@id= 'Case_IsAnonymousComplainant']",
          'salutation'                                =>    "xpath^^.//*[@id='Case_Complainant_SalutationId']",
          'first name'                                =>    "xpath^^.//*[@id='Case_Complainant_FirstName']",
          'last name'                                 =>    "xpath^^.//*[@id='Case_Complainant_LastName']",
          'age years'                                 =>    "xpath^^.//*[@id='Case_ComplainantAgeListId']",
          'age'                                       =>    "xpath^^.//*[@id='Case_ComplainantAge']",
          'age:error message'                         =>    "xpath^^.//*[@id='Case_ComplainantAge-error']",
          'on behalf of: salutation'                  =>    "xpath^^.//*[@id='Case_OnBehalfOfSalutationId']",
          'on behalf of: first name'                  =>    "xpath^^.//*[@id='Case_OnBehalfOfFirstName']",
          'on behalf of: last name'                   =>    "xpath^^.//*[@id='Case_OnBehalfOfLastName']",
          'on behalf of: age years'                   =>    "xpath^^.//*[@id='Case_OnBehalfOfAgeListId']",
          'on behalf of: age'                         =>    "xpath^^.//*[@id='Case_OnBehalfOfAge']",
          'address1'                                  =>    "xpath^^.//*[@id='Case_Complainant_AddressLineOne']",
          'address2'                                  =>    "xpath^^.//*[@id='Case_Complainant_AddressLineTwo']",
          'city'                                      =>    "xpath^^.//*[@id='Case_Complainant_City']",
          'country'                                   =>    "xpath^^.//*[@id='Case_Complainant_CountryId']",
          'state'                                     =>    "xpath^^.//*[@id='Case_Complainant_StateId']",
          'state:error message'                       =>    "xpath^^.//*[@id='Case_Complainant_StateId-error']",
          'other country state'                       =>    "xpath^^.//*[@id='Case_Complainant_StateName']",
          'zip code'                                  =>     "xpath^^.//*[@id='Case_Complainant_Zip']",
          'zip code:error message'                    =>      "xpath^^.//*[@id='Case_Complainant_Zip-error']",
          'district'                                  =>    "css^^#Case_District",
          'incident date:error message'               =>    "xpath^^.//*[@id='Case_DateOfIncident-error']",
          'complaint data:contact information-label'  =>    "xpath^^.//*[@id='contactTypesDiv1']/h5",
          'complaint data:contact information:contact type-label'   =>    "xpath^^.//*[@id='ContactsTable1']/descendant::th[1]",
          'complaint data:contact information:contact info-label'   =>    "xpath^^.//*[@id='ContactsTable1']/descendant::th[2]",
          'complaint data:contact information:action-label'         =>    "xpath^^.//*[@id='ContactsTable1']/descendant::th[3]",
          'complaint data:contact information:add contact'          =>   "xpath^^.//*[@id='newContactType1']",
          'complaint data:add contact:contact type-field'           =>    "xpath^^.//*[@id='Contact_Options']",
          'complaint data:add contact:contact details-field'        =>    "xpath^^.//*[@id='Contact_Details']",
          'complaint data:add contact:contact details-error'        =>    "xpath^^.//*[@id='Contact_Details-error']",
          'complaint data:add contact:add-field'                    =>    "xpath^^.//*[@id='Contact_Add']",
          'complaint data:add contact:cancel-field'                 =>    "xpath^^.//*[@id='Contact_Cancel']"
      }
end