def map_exports_librarian
@page_objects['exports_librarian'] =


    {
        #Export librarian, adding a country.
        'role drop down'                                   =>"xpath^^.//*[@id='ctl00_ctl00_UserRoleDropDownList']",
        'country drop down'                                =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_AppMenuBar']/ul/li[1]/a/span/span[1]",
        'select country'                                   =>"xpath^^.//*[contains(text(), 'elect Country')]",
        'country selection page'                           =>"xpath^^.//*[contains(text(), 'Country Selection')]",
        'country profile page'                             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSectionCountryNm']",
        'country selection drop down'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_DDLCountry']",
        'country profile'                                  =>"xpath^^//div[@id='ctl00_ctl00_ContentPlaceHolder1_AppMenuBar']/ul/li/div/ul/li[2]/a/span/span[2]",
        'add new file'                                     =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_rgUploadDocuments_ctl00_ctl02_ctl00_lnkAddNewFile']",
        'browse new file'                                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_fileUpload']",
        'document tittle text box'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_txtDocumentTitle']",
        'upload document button'                           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_btnUpload']",
        'cancel upload document button'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_btnCancel']",
        'save upload document button'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_submitUpdateCountryProfileBtn']",
        'upload document success message display'          =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_lblDisplayMessage']",
        'save button on country profile'                   =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_submitUpdateCountryProfileBtn']",
        'signature type: edit country profile'             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_signTypecb_1']",
        'allow multiple species on export certificate no: edit country profile'             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_allowMultSpeciesRbl_0']",
        'celsius: edit country profile'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_tempScaleRbl_0']",
        'rule collection: create a rule collection'        =>"xpath^^.//*[contains(text(), 'ule Collections')]",
        'rule collection: name'                            =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_Name']",
        'rule collection: description'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_Description']",
        'rule collection: save button'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_docSubmit']",
        'rule collection: edit description in collection' =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_txtCollectionDesc']",
        'rule collection: new collection added'           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radRuleCollections']//*[contains(text(), 'Automation_Test_Date112')]",
        'rule collection: edit new collection added'      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radRuleCollections']//*[contains(text(), 'Edited Automation Test Description data.')]",
        'return to rule collection'                       =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radBtnRuleCollection']",
        'validator name text box'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_Name']",
        'validator description text box'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_Description']",
        'validator create button'                         =>"xpath^^.//*[contains(@value, 'Create')]",
        'new validated added'                             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radValidatorCollections_ctl00']//*[contains(text(), 'Automation_Test_Date112')]",
        'validator class drop down'                       =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlClass']",
        'validator outside box'                          =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_tblRuleSet']/tbody/tr[2]/td[3]",
        'save button: validator'                         =>"xpath^^.//*[contains(@value, 'Save')]",
        'species not added alert message: validator'     =>"xpath^^.//*[contains(text(), 'The Species criteria is invalid. No values were selected.')]",
        'validator species drop down'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlSpecies']",
        'vendor not added alert message: validator'     =>"xpath^^.//*[contains(text(), 'No validators were selected. At least one criterion has to be selected as a validator.')]",
        'species selected section'                       =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_selectedSpecies']",
        'species select drop down arrow'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlSpecies_Arrow']",
        'check box to select validator'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_cbSelectorHACCP']/span[1]",
        'selector check box'                             =>"xpath^^//tbody/tr[6]/td//*[contains(text(), 'Selector')]",
        'validator check box'                             =>"xpath^^//tbody/tr[6]/td//*[contains(text(), 'Validator')]",
        'operation field drop down'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlHaccpOperator']",
        'validator category drop down'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlHaccpCategory']",
        'category select drop down arrow'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlHaccpCategory_Arrow']",
        'validator rule set update success alert'          =>"xpath^^.//*[contains(text(), 'Validator rule set is updated successfully.')]",
        'validator delete success message'                 =>"xpath^^.//*[contains(text(), 'Validator deleted successfully.')]",
        'submit button: validator record for approval'     =>"xpath^^.//*[contains(@value, 'Submit')]",
        'validator rule set submit success alert'          =>"xpath^^.//*[contains(text(), 'Validator rule set is submitted successfully.')]",
        'pending validator radio button'                   =>"xpath^^.//*[contains(@value, 'Pending')]",
        'pending validator record'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radValidatorCollections_ctl00']/tbody/tr//*[contains(text(), 'Automation_Test_Date112')]",
        'instructions tab'                                 =>"xpath^^.//*[contains(text(), 'Instructions (0-0-0)')]",
        'instruction name text box'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_IName']",
        'instruction description text box'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_IDescription']",
        'instruction warn for unique data alert'          =>"xpath^^.//*[contains(text(), 'Rule set name must be unique within its country.')]",
        'instruction success creation alert'              =>"xpath^^.//*[contains(text(), 'New instruction added successfully.')]",
        'new radio button'                                =>"xpath^^.//*[contains(@value, 'NonPublished')]",
        'new instruction record table'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radInstructionCollections_ctl00']/tbody/tr//*[contains(text(), 'Automation_Test_Instruction101')]",
        'instruction create button'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_docSubmitInstruction']",
        'number of phv signature checkbox'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_cbPHVSignatures']",
        'certificate checkbox'                              =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_cbCertificates']",
        'certificate drop down'                           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ddlCertificates']",
        'class field drop down'                           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlClass']",
        'alert message to set instruction rule'           =>"xpath^^.//*[contains(text(), 'Instruction rule set is invalid. Number of PHV Signatures was selected, but no values were specified.')]",
        'instruction species drop down'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlSpecies']",
        'instruction haccp type check box'                 =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_cbSelectorHACCP']/span[1]",
        'shipping type check box'                          =>"xpath^^//tbody/tr[6]/td//*[contains(text(), 'N/A')]",
        'instruction selector check box'                 =>"xpath^^//tbody/tr[6]/td//*[contains(text(), 'Selector')]",
        'instruction field drop down'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlHaccpOperator']",
        'instruction category drop down'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlHaccpCategory']",
        'instruction phv signature alert'                  =>"xpath^^.//*[contains(text(), 'Instruction rule set is invalid. Number of PHV Signatures was selected, but no values were specified.')]",
        'phv signature: not required'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_rbPHVSignatures_0']",
        'instruction: updated success alert'            =>"xpath^^.//*[contains(text(), 'Instruction rule set is updated successfully.')]",
        'instruction: species edited'                   =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_selectedSpecies']",
        'instruction delete success message container'  =>"xpath^^.//*[contains(text(), 'Instruction deleted successfully.')]",
        'pending instruction record'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radInstructionCollections_ctl00']/tbody/tr//*[contains(text(), 'Automation_Test_Instruction101')]",
        'instruction rule set submit success alert'     =>"xpath^^.//*[contains(text(), 'Instruction rule set is submitted successfully.')]",
        'submit button: instruction record for approval'     =>"xpath^^.//*[contains(@value, 'Submit')]",

        #Approving a Validator.
        'country approval admin: left navigation'     =>"xpath^^.//*[contains(text(), 'ountry Approvals Admin')][contains(@class, 'rpText')]",
        'rule set approval: left navigation'         =>"xpath^^.//*[contains(text(), 'ule Set Approval')][contains(@class, 'rpText')]",
        'approval confirmation for approved validator' =>"xpath^^.//*[contains(text(), 'The operation was completed successfully.')]",
        'published: validator record'                =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_rcbShow_0']",
        'approved validator record'                   =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radValidatorCollections_ctl00']/tbody/tr//*[contains(text(), 'Automation_Test_Date112')]",
        'rejected validator record: validator status' =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radValidatorCollections_ctl00']/tbody/tr//*[contains(text(), 'Rejected')]",
        'approved instruction record: instruction status' =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radInstructionCollections_ctl00']/tbody/tr//*[contains(text(), 'Automation_Test_Instruction101')]",
        'instruction delete success message'             =>"xpath^^.//*[contains(text(), 'Instruction deleted successfully.')]",
        'rejected instruction record: validator status' =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radInstructionCollections_ctl00']/tbody/tr//*[contains(text(), 'Rejected')]",
        #Data Admin.
        'ref data management'                           =>"xpath^^.//*[contains(text(), 'ef Data Management')]",
        'ref countries'                                =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_reftableTree']/ul/li[68]/div/span[3]",
        'ref countries save button'                     =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_btnSave']",
        'ref data management data save alert'          =>"xpath^^.//*[contains(text(), 'The entered values are saved successfully')]",
        '9060 left nav'                                =>"xpath^^//*[contains (@id, 'ctl00_ctl00_ContentPlaceHolder1_AppMenuBar')]//*[contains(text(), '060')]",
        '9060: shipment type drop down'                =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ddlShipmentType']",
        '9060: application type drop down'             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ddlApplicationType']",
        'next button'                                  =>"xpath^^.//*[contains(@value, 'Next')]",
        '9060: company name'                          =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_txtCompany']",
        '9060: company address1'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_txtAddress1']",
        '9060: company address2'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_txtAddress2']",
        '9060: company address3'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_txtAddress3']",
        '9060: city'                                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_txtCity']",
        '9060: country drop down'                     =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_ddlCountry']",
        '9060: state province drop down'              =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_ddlState']",
        '9060: postal code'                           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_txtZipCode']",
        '9060: invalid postal code alert'             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_RegularExpressionValidator2']",
        '9060: phone number'                           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_txtPhoneNumber']",
        '9060: export establishment drop down'        =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_EstablishmentNumberOnApplicationControl_ddlEstNumOnApp']",
        '9060: unique identifier check'               =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_rdExportMarkToBeUsed_1']",
        '9060: unique identifier tex tbx'               =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_txtUniqueIdentifier']",
        '9060: data error alert'                      =>"xpath^^.//*[contains(text(), 'Data could not be saved due to the errors below.')]",
        '9060: address lin1 required indicator'       =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_rfvAddress1']",
        '9060: city required indicator'               =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_rfvCity']",
        '9060: state required indicator'              =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_rfvState']",
        '9060: postal code required indicator'        =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_AddressInformationControl_rfvZipCode']",
        '9060: export establishment required indicator' =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_EstablishmentNumberOnApplicationControl_rfvEstNumOnApp']",
        '9060: application number holder'              =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ExportApplication9060Header_lblApplicationNumber']",
        '9060: final destination country drop down'   =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ddlFinalDestinationCountry']",
        '9060: final destination port drop down'     =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ddlFinalDestinationPort']",
        'exit menu left nav'                          =>"xpath^^.//*[contains(text(), 'xit Menu')]",
        'isexport check box'                          =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_isExport']",
        'application number filter text box'          =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radGrid9060Applications_ctl00_ctl02_ctl03_FilterTextBox_ApplicationNumber']",
        'application number filter icon'              =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radGrid9060Applications_ctl00_ctl02_ctl03_Filter_ApplicationNumber']",
        'application number filter contains'         =>"xpath^^.//*[contains(text(), 'Contains')][contains(@class, 'rmText')]",
        '9060: edit icon'                            =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radGrid9060Applications_ctl00_ctl04_imgHome1']",
        '9060: importer left nav'                    =>"xpath^^.//*[contains(text(), 'Importer')]",
        '9060: delete icon'                           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radGrid9060Applications_ctl00_ctl04_imgDeleteApp']",
        '9060: no record message on table'            =>"xpath^^.//*[contains(text(), 'No records to display.')]",
        '9060: ok button'                             =>"xpath^^//table/tbody//*[contains(text(), 'OK')]",
        '9060: approved validator status'             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetHeader_lblStatus']",
        '9060: cancel button'                         =>"xpath^^.//*[contains(@value, 'Cancel')]",
        '9060: test rule sets left nav'               =>"xpath^^.//*[contains(text(), 'est Rule Sets')]",
        '9060: shipping type drop down'               =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ddlST']",
        '9060: species type drop down'               =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_rgForm9060_ctl00_ctl02_ctl02_ddlSpecies']",
        '9060: haccp type drop down'                 =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_rgForm9060_ctl00_ctl02_ctl02_ddlHACCP']",
        '9060: maturity type drop down'              =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_rgForm9060_ctl00_ctl02_ctl02_ddlMaturity']",
        '9060: run test button'                      =>"xpath^^.//*[contains(@value, 'Run Test')]",
        '9060: run test result status'                =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_rgForm9060_ctl00']//*[contains(text(), 'Pass')][contains(@class, 'st-pass')]",
        '9060: update test button'                    =>"xpath^^.//*[contains(@value, 'Update Test')]",
        'rule test: instruction radio button'         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_rbInstr']",
        'rule test: instruction result signature'     =>"xpath^^.//*[contains(text(), 'PHV Signatures required.')]",
        'rule test: instruction result transit signature'     =>"xpath^^.//*[contains(text(), 'No PHV Signatures are required.')]",
        'rule test: instruction result transit certificate'   =>"xpath^^.//*[contains(text(), 'No Certificates are required.')]",









    }
end