def map_exports_librarian
@page_objects['exports_librarian'] =


    {
        #Export librarian, adding a country.
        'role drop down'                                   =>"xpath^^.//*[@id='ctl00_ctl00_UserRoleDropDownList']",
        'country drop down'                                =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_AppMenuBar']/ul/li[1]/a/span/span[1]",
        'select country'                                   =>"xpath^^.//*[contains(text(), 'elect Country')]",
        'country selection page'                           =>"xpath^^.//*[contains(text(), 'Country Selection')]",
        'country profile page'                             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSectionCountryNm']",
        'country selection drop down'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_DDLCountry']",
        'country profile'                                  =>"xpath^^//div[@id='ctl00_ctl00_ContentPlaceHolder1_AppMenuBar']/ul/li/div/ul/li[2]/a/span/span[2]",
        'add new file'                                     =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_rgUploadDocuments_ctl00_ctl02_ctl00_lnkAddNewFile']",
        'browse new file'                                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_fileUpload']",
        'document tittle text box'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_txtDocumentTitle']",
        'upload document button'                           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_btnUpload']",
        'cancel upload document button'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_btnCancel']",
        'save upload document button'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_submitUpdateCountryProfileBtn']",
        'upload document success message display'          =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_UploadDocuments_lblDisplayMessage']",
        'save button on country profile'                   =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_submitUpdateCountryProfileBtn']",
        'signature type: edit country profile'             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_signTypecb_1']",
        'allow multiple species on export certificate no: edit country profile'             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_allowMultSpeciesRbl_0']",
        'celsius: edit country profile'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_tempScaleRbl_0']",
        'rule collection: create a rule collection'        =>"xpath^^.//*[contains(text(), 'ule Collections')]",
        'rule collection: name'                            =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_Name']",
        'rule collection: description'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_Description']",
        'rule collection: save button'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_docSubmit']",
        'rule collection: edit description in collection' =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_txtCollectionDesc']",
        'rule collection: new collection added'           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radRuleCollections']//*[contains(text(), 'Automation_Test_Date112')]",
        'rule collection: edit new collection added'      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radRuleCollections']//*[contains(text(), 'Edited Automation Test Description data.')]",
        'return to rule collection'                       =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radBtnRuleCollection']",
        'validator name text box'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_Name']",
        'validator description text box'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_Description']",
        'validator create button'                         =>"xpath^^.//*[contains(@value, 'Create')]",
        'new validated added'                             =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radValidatorCollections_ctl00']//*[contains(text(), 'Automation_Test_Date112')]",
        'validator class drop down'                       =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlClass']",
        'validator outside box'                          =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_tblRuleSet']/tbody/tr[2]/td[3]",
        'save button: validator'                         =>"xpath^^.//*[contains(@value, 'Save')]",
        'species not added alert message: validator'     =>"xpath^^.//*[contains(text(), 'The Species criteria is invalid. No values were selected.')]",
        'validator species drop down'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlSpecies']",
        'vendor not added alert message: validator'     =>"xpath^^.//*[contains(text(), 'No validators were selected. At least one criterion has to be selected as a validator.')]",
        'species selected section'                       =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_selectedSpecies']",
        'species select drop down arrow'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlSpecies_Arrow']",
        'check box to select validator'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_cbSelectorHACCP']/span[1]",
        'selector check box'                             =>"xpath^^//tbody/tr[6]/td//*[contains(text(), 'Selector')]",
        'validator check box'                             =>"xpath^^//tbody/tr[6]/td//*[contains(text(), 'Validator')]",
        'operation field drop down'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlHaccpOperator']",
        'validator category drop down'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlHaccpCategory']",
        'category select drop down arrow'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlHaccpCategory_Arrow']",
        'validator rule set update success alert'          =>"xpath^^.//*[contains(text(), 'Validator rule set is updated successfully.')]",
        'validator delete success message'                 =>"xpath^^.//*[contains(text(), 'Validator deleted successfully.')]",
        'submit button: validator record for approval'     =>"xpath^^.//*[contains(@value, 'Submit')]",
        'validator rule set submit success alert'          =>"xpath^^.//*[contains(text(), 'Validator rule set is submitted successfully.')]",
        'pending validator radio button'                   =>"xpath^^.//*[contains(@value, 'Pending')]",
        'pending validator record'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radValidatorCollections_ctl00']/tbody/tr//*[contains(text(), 'Automation_Test_Date112')]",
        'instructions tab'                                 =>"xpath^^.//*[contains(text(), 'Instructions (0-0-0)')]",
        'instruction name text box'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_IName']",
        'instruction description text box'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_IDescription']",
        'instruction warn for unique data alert'          =>"xpath^^.//*[contains(text(), 'Rule set name must be unique within its country.')]",
        'instruction success creation alert'              =>"xpath^^.//*[contains(text(), 'New instruction added successfully.')]",
        'new radio button'                                =>"xpath^^.//*[contains(@value, 'NonPublished')]",
        'new instruction record table'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_radInstructionCollections_ctl00']/tbody/tr//*[contains(text(), 'Automation_Test_Instruction101')]",
        'instruction create button'                         =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_docSubmitInstruction']",
        'number of phv signature checkbox'                  =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_cbPHVSignatures']",
        'certificate checkbox'                              =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_cbCertificates']",
        'certificate drop down'                           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ddlCertificates']",
        'class field drop down'                           =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlClass']",
        'alert message to set instruction rule'           =>"xpath^^.//*[contains(text(), 'Instruction rule set is invalid. Number of PHV Signatures was selected, but no values were specified.')]",
        'instruction species drop down'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlSpecies']",
        'instruction haccp type check box'                 =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_cbSelectorHACCP']/span[1]",
        'shipping type check box'                          =>"xpath^^//tbody/tr[6]/td//*[contains(text(), 'N/A')]",
        'instruction selector check box'                 =>"xpath^^//tbody/tr[6]/td//*[contains(text(), 'Selector')]",
        'instruction field drop down'                      =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlHaccpOperator']",
        'instruction category drop down'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_ddlHaccpCategory']",
        'instruction phv signature alert'                  =>"xpath^^.//*[contains(text(), 'Instruction rule set is invalid. Number of PHV Signatures was selected, but no values were specified.')]",
        'phv signature: not required'                    =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_rbPHVSignatures_0']",
        'instruction: updated success alert'            =>"xpath^^.//*[contains(text(), 'Instruction rule set is updated successfully.')]",
        'instruction: species edited'                   =>"xpath^^.//*[@id='ctl00_ctl00_ContentPlaceHolder1_ContentPlaceHolder1_ruleSetInfo_selectedSpecies']",
        'instruction delete success message container'  =>"xpath^^.//*[contains(text(), 'Instruction deleted successfully.')]",

    }
end